CREATE TABLE BOARD(
        BOARD_IDX NUMBER(10) PRIMARY KEY, -- 글번호
        FESTA_ID VARCHAR2(20) NOT NULL, --페스티벌 ID
        MEM_IDX NUMBER(30) NOT NULL, --작성자 IDX
        BOARD_TITLE VARCHAR2(150) NOT NULL, -- 제목
        BOARD_CONTENT VARCHAR2(5000) NOT NULL, --게시글 내용
        BOARD_DATE DATE DEFAULT SYSDATE NOT NULL --작성날짜
);

CREATE SEQUENCE BOARD_IDX_SEQ
    START WITH 1
    INCREMENT BY 1;