CREATE TABLE REPLY(
       REPLY_BOARD_IDX NUMBER NOT NULL, --게시글 번호
       REPLY_IDX NUMBER PRIMARY KEY, -- 댓글 번호
       REPLY_MEM_ID NUMBER NOT NULL, -- 댓글 작성자 ID, 회원정보의 ID와 매치
       REPLY_CONTENT VARCHAR2 (2000) NOT NULL, -- 댓글 내용
       REPLY_DATE DATE DEFAULT SYSDATE NOT NULL -- 댓글 작성날짜
);

CREATE SEQUENCE REPLY_IDX_SEQ
START WITH 1
INCREMENT BY 1;